version: "3"
services:
  postgres:
    container_name: duckling-postgres
    image: postgres:latest
    ports:
      - "5447:5432"
    volumes:
      - ./tmp/data/postgres:/data/postgres
    env_file:
      - docker.env
