components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the organization.
        name:
          type: string
          description: The name of the organization.
        createdAt:
          type: string
          format: date-time
          description: The date and time when the organization was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time when the organization was last updated.
