name: Build and Startup Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.7.0'

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build the project
      - name: Build
        run: yarn build

      # Start the app and wait for 10 seconds
      - name: Start and wait
        run: |
          echo "Starting the application..."
          yarn start &
          APP_PID=$!
          echo "Application started with PID $APP_PID. Waiting for 10 seconds to ensure it stays running..."
          sleep 10
          if kill -0 $APP_PID; then
            echo "Application is still running. Proceeding..."
            kill $APP_PID
          else
            echo "Application is not running. Failing the check."
            exit 1
          fi
